# Generated by Django 5.2.3 on 2025-06-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
