# Generated by Django 5.2.17 on 2026-10-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="pms_tenant_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="pms_transaction_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("charge", "Charge"), ("payment", "Payment")],
                default="",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
