# Generated by Django 5.2.17 on 2026-10-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_pms_identifiers_and_transaction_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["date", "id"]},
        ),
    ]
